#!/usr/bin/env bash
# displays content of /etc/passwd, limited to usernames, user ids, and home directories - using while loop

while read -r passwd
do
	echo "$passwd" | cut -d ":" -f1,3,6
done < "/etc/passwd"	
