#!/usr/bin/env bash
# tells a somewhat repetitive but riveting tale of the denizens living in the land of /etc/passwd - using while and IFS

while IFS=':' read -r USERNAME PASSWORD USER_ID GROUP_ID USER_ID_INFO HOME_DIRECTORY COMMANDSHELL
do
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMANDSHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done < "/etc/passwd"
