#!/usr/bin/env bash
# This script displays numbers 1-20 except line 5 ("bad luck from China"), line 10 ("bad luck from Japan"), and line 18 ("bad luck from Italy")
i=1
while [ $i -le 20 ]
do
	case $i in
		4)
			echo "$i"
			echo "bad luck from China"
			;;
		9)
			echo "$i"
			echo "bad luck from Japan"
			;;
		17)
			echo "$i"
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
	esac
	((i++))
done
